# Generated by Django 5.1.3 on 2024-11-19 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='board_tasks', to='core.board', verbose_name='Доска'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_tasks', to='core.list', verbose_name='Список'),
        ),
    ]
