# Generated by Django 5.1.3 on 2024-11-23 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_board_alter_task_labels_alter_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='position',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 30, 2, 4, 40, 902123, tzinfo=datetime.timezone.utc), null=True, verbose_name='Срок выполнения'),
        ),
    ]
