# Generated by Django 5.1.3 on 2024-11-24 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_list_position_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 1, 21, 44, 23, 816801, tzinfo=datetime.timezone.utc), null=True, verbose_name='Срок выполнения'),
        ),
    ]
