# Generated by Django 5.1.3 on 2024-12-02 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 12, 9, 19, 28, 20, 110904, tzinfo=datetime.timezone.utc), null=True, verbose_name='Срок выполнения'),
        ),
    ]
